server :
  port : 8081

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/book-library
    username : root
    password : root

  application:
    name: BOOK-SUBSCRIPTION-SERVICE

  jpa:
      hibernate:
        database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto : update

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      bookService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      bookService:
        maxRetryAttempts: 5
        waitDuration: 10s